language: node_js
node_js:
  - node
cache: npm

services:
  - docker
  - mysql
addons:
  mariadb: '10.3.13'

env:
  - NODE_ENV=testing

before_script:
  - set -e
  - mysql -e 'create database tenutest'
  - mysql -e "create user 'tenudev'@'localhost' IDENTIFIED BY 'hamzaoutai';"
  - mysql -e "grant all on tenutest.* to 'tenudev'@'localhost';"
  - cd backend
  - npm ci
  - cd ../frontend
  - npm ci
  - npm i codecov
  - cd ..

script:
  - set -e

  # Environment variables
  - export REPO_NAME=$(echo $TRAVIS_REPO_SLUG | awk -F/ '{ print tolower($2) }')

  # Backend
  - cd backend
  - npm run lint
  - npm test
  - npm run apidoc
  - cd ..

  # Frontend
  - cd frontend
  - npm test -- --coverage
  - ./node_modules/.bin/codecov
  - npm run lint
  - npm run build
  - cd ..

   # Build Docker
  - docker build -t ebm2018/$REPO_NAME:latest .
  - |
    if [[ $TRAVIS_BRANCH == 'master' ]] && [[ $TRAVIS_PULL_REQUEST == 'false' ]];
      then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push "ebm2018/$REPO_NAME:latest"
    fi;

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: backend/doc
  on:
    branch: master
