version: "3"

services:
  web:
    image: ebm2018/tenugui:latest
    depends_on:
      - mariadb
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=TenuGUI
      - DB_USERNAME=Tenuguy
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_LOGGING=false
    networks:
      local:
      ebm-filrouge:
        aliases:
          - tenugui
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:tenugui.ebm.nymous.io"
      - "traefik.port=4000"
      - "traefik.network=ebm-filrouge"
      - "com.centurylinklabs.watchtower.enable=true"
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: TenuGUI
      MYSQL_USER: Tenuguy
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - local

networks:
  local:
  ebm-filrouge:
    external: true
