version: "3"

services:
  web:
    image: ebm2018/tenugui:latest
    # depends_on:
    #   - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb/tenugui
    networks:
      local:
      ebm-filrouge:
        aliases:
          - tengui
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:tenugui.ebm.nymous.io"
      - "traefik.port=4000"
      - "traefik.network=ebm-filrouge"
      - "com.centurylinklabs.watchtower.enable=true"
  # mongodb:
  #   image: mongo
  #   networks:
  #     - local

networks:
  local:
  ebm-filrouge:
    external: true
