version: "3"
services:
  web:
    image: ebm2018/filrouge-boilerplate:latest
    # depends_on:
    #   - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb/filrouge-boilerplate
    networks:
      local:
      ebm-filrouge:
        aliases:
          - filrouge-boilerplate
  # mongodb:
  #   image: mongo
  #   networks:
  #     - local
networks:
  local:
  ebm-filrouge:
    external: true
